## code to prepare `mini_consumption` dataset goes here

library(DBI)

# connect to local Postgres database (or HEROKU moving forward)
con <- dbConnect(RPostgres::Postgres(),
                 dbname=Sys.getenv("POSTGRES_DB"),
                 host="localhost",
                 port="5432",
                 user=Sys.getenv("POSTGRES_USER"),
                 password=Sys.getenv("POSTGRES_PASSWORD"))

# Check that connection is established by checking which tables are present
dbListTables(con)

# Pull data
consumption <- dbGetQuery(con, "SELECT * FROM consumption") %>%
  select(-record_id)

# Close database connection
dbDisconnect(con)

rm(list = c("con"))

# Get 100 samples from data
set.seed(123)
sample <- consumption[sample(nrow(consumption), 100), ]
dput(sample)

mini_consumption <- data.frame(year = c(2016, 2017, 2003, 1997, 2010, 1999, 2004, 
                                                2013, 2018, 2009, 2007, 2014, 1999, 2005, 2013, 2015, 2002, 2009, 
                                                2009, 2014, 2002, 2005, 2010, 1996, 2010, 2007, 1997, 2004, 2009, 
                                                2001, 2005, 2002, 2012, 2015, 2018, 2014, 2010, 2013, 2009, 2011, 
                                                2019, 2016, 1996, 1997, 2012, 2011, 2014, 2011, 1999, 2001, 2001, 
                                                1998, 2007, 2007, 2010, 2007, 1999, 2002, 2000, 2007, 2005, 2007, 
                                                2010, 2012, 2010, 2017, 2009, 2018, 2018, 2015, 2002, 2006, 2000, 
                                                2017, 1998, 2014, 2008, 2006, 2002, 1998, 2012, 2018, 2000, 2007, 
                                                2019, 2015, 2008, 2011, 2001, 2019, 2006, 2015, 2019, 2015, 2014, 
                                                2014, 2015, 2004, 2019, 2012), hs_version = c("HS12", "HS12", 
                                                                                              "HS96", "HS96", "HS07", "HS96", "HS02", "HS12", "HS12", "HS02", 
                                                                                              "HS02", "HS12", "HS96", "HS02", "HS12", "HS12", "HS96", "HS02", 
                                                                                              "HS02", "HS12", "HS96", "HS02", "HS07", "HS96", "HS07", "HS02", 
                                                                                              "HS96", "HS02", "HS02", "HS96", "HS02", "HS96", "HS07", "HS12", 
                                                                                              "HS12", "HS12", "HS07", "HS12", "HS02", "HS07", "HS12", "HS12", 
                                                                                              "HS96", "HS96", "HS07", "HS07", "HS12", "HS07", "HS96", "HS96", 
                                                                                              "HS96", "HS96", "HS02", "HS02", "HS07", "HS02", "HS96", "HS96", 
                                                                                              "HS96", "HS02", "HS02", "HS02", "HS07", "HS07", "HS07", "HS12", 
                                                                                              "HS02", "HS12", "HS12", "HS12", "HS96", "HS02", "HS96", "HS12", 
                                                                                              "HS96", "HS12", "HS02", "HS02", "HS96", "HS96", "HS07", "HS12", 
                                                                                              "HS96", "HS02", "HS12", "HS12", "HS02", "HS07", "HS96", "HS12", 
                                                                                              "HS02", "HS12", "HS12", "HS12", "HS12", "HS12", "HS12", "HS02", 
                                                                                              "HS12", "HS07"), source_country_iso3c = c("THA", "TWN", "IDN", 
                                                                                                                                        "TUR", "MYS", "ECU", "KOR", "TUR", "unknown", "SEN", "GBR", "ESP", 
                                                                                                                                        "unknown", "TWN", "MYS", "USA", "MYS", "CHN", "NIC", "CHN", "unknown", 
                                                                                                                                        "EST", "USA", "PAN", "GBR", "BRA", "GBR", "FRA", "CHN", "MAR", 
                                                                                                                                        "unknown", "NZL", "MUS", "IDN", "CHN", "TZA", "ESP", "RUS", "KOR", 
                                                                                                                                        "CHN", "COL", "IND", "ESP", "PRT", "CHN", "OMN", "THA", "IDN", 
                                                                                                                                        "CHN", "PRT", "IRL", "SEN", "AUS", "NZL", "CHN", "BGD", "IDN", 
                                                                                                                                        "FRA", "unknown", "unknown", "RUS", "FRA", "DNK", "NLD", "ESP", 
                                                                                                                                        "TWN", "PER", "CAN", "ESP", "JPN", "THA", "NLD", "ARG", "GBR", 
                                                                                                                                        "TUR", "VNM", "CHN", "BRA", "KOR", "TWN", "DNK", "MEX", "ITA", 
                                                                                                                                        "VNM", "ESP", "IRN", "FRA", "MRT", "NOR", "IND", "AUS", "ARG", 
                                                                                                                                        "CAN", "IND", "IDN", "MLT", "MEX", "FRA", "unknown", "IDN"), 
                                       exporter_iso3c = c("USA", NA, "TWN", "TUR", "MYS", "AUS", 
                                                          "USA", "DEU", "RUS", "SEN", "FRA", "ESP", "ITA", "TWN", "MYS", 
                                                          "PRT", "IDN", "CHN", "ESP", "CHN", "AUS", "RUS", "CHN", "CAN", 
                                                          "GBR", "USA", "GBR", "DEU", "CHN", "GBR", "THA", "NZL", "TWN", 
                                                          "CHN", "SAU", "ARE", "THA", "GBR", "NZL", "SGP", "ECU", "VNM", 
                                                          "HND", "CAN", "CAN", "OMN", "THA", "SGP", "TWN", "ESP", "NLD", 
                                                          "SEN", NA, "NZL", "CHN", "POL", "IDN", "NLD", "CAN", "ESP", 
                                                          "EST", "FRA", "DNK", "JPN", "LTU", "THA", "COL", "NLD", "DNK", 
                                                          "RUS", "SGP", "POL", "ARG", "GBR", "TUR", "JOR", "CHN", "BRA", 
                                                          "KOR", "NLD", "GBR", "TWN", "GBR", "ISL", "ESP", "IRN", "GBR", 
                                                          "ESP", "DEU", "PHL", "CHN", "ARG", "CAN", "LKA", "ROU", "ESP", 
                                                          "CHN", "FRA", "DNK", "CHN"), consumer_iso3c = c("JPN", "TWN", 
                                                                                                          "IDN", "NLD", "MUS", "JPN", "ITA", "SWE", "MNG", "GEO", "RUS", 
                                                                                                          "HND", "PRT", "RUS", "USA", "ITA", "USA", "PNG", "BEL", "CIV", 
                                                                                                          "AZE", "MDA", "PRT", "CZE", "CMR", "CAN", "FRA", "POL", "PHL", 
                                                                                                          "DEU", "DNK", "EGY", "EGY", "NGA", "USA", "SOM", "SLV", "NOR", 
                                                                                                          "ZAF", "BRN", "DEU", "CHN", "USA", "DEU", "KNA", "GBR", "FJI", 
                                                                                                          "BGD", "JPN", "NGA", "GEO", "DEU", "AUS", "POL", "USA", "SWE", 
                                                                                                          "MEX", "SWE", "MLT", "TUN", "RUS", "THA", "VNM", "THA", "BLR", 
                                                                                                          "DJI", "ESP", "ITA", "NOR", "THA", "GRC", "LTU", "NLD", "PAK", 
                                                                                                          "FRA", "VNM", "BRA", "ESP", "SVN", "EGY", "EST", "KOR", "FRA", 
                                                                                                          "EST", "MAR", "OMN", "RUS", "BFA", "JPN", "TWN", "TWN", "AUS", 
                                                                                                          "VNM", "JPN", "FRA", "MDG", "PHL", "CZE", "BLR", "RUS"), 
                                       dom_source = c("foreign", NA, "foreign", "domestic", "domestic", 
                                                      "foreign", "foreign", "foreign", "foreign", "domestic", "foreign", 
                                                      "domestic", "foreign", "domestic", "domestic", "foreign", 
                                                      "foreign", "domestic", "foreign", "domestic", "foreign", 
                                                      "foreign", "foreign", "foreign", "domestic", "foreign", "domestic", 
                                                      "foreign", "foreign", "foreign", "error", "domestic", "foreign", 
                                                      "foreign", "foreign", "foreign", "foreign", "foreign", "foreign", 
                                                      "foreign", "foreign", "foreign", "foreign", "foreign", "foreign", 
                                                      "domestic", "domestic", "foreign", "foreign", "foreign", 
                                                      "foreign", "domestic", NA, "domestic", "domestic", "foreign", 
                                                      "domestic", "foreign", "foreign", "foreign", "foreign", "domestic", 
                                                      "domestic", "foreign", "foreign", "foreign", "foreign", "foreign", 
                                                      "foreign", "foreign", "foreign", "foreign", "domestic", "domestic", 
                                                      "domestic", "foreign", "domestic", "domestic", "domestic", 
                                                      "foreign", "foreign", "foreign", "foreign", "foreign", "domestic", 
                                                      "domestic", "foreign", "foreign", "foreign", "foreign", "foreign", 
                                                      "domestic", "domestic", "foreign", "foreign", "foreign", 
                                                      "foreign", "domestic", "foreign", "foreign"), sciname = c("lates calcarifer", 
                                                                                                                "thunnus alalunga", "metapenaeus", "belone belone", "polynemidae", 
                                                                                                                "litopenaeus stylirostris", "cephalopoda", "alburnus tarichi", 
                                                                                                                "scombrinae", "actinopterygii", "micromesistius poutassou", 
                                                                                                                "octopus vulgaris", "clupea", "sphyraena", "katsuwonus pelamis", 
                                                                                                                "oncorhynchus tshawytscha", "hypophthalmichthys nobilis", 
                                                                                                                "decapterus", "litopenaeus vannamei", "haemulidae", NA, "perca fluviatilis", 
                                                                                                                "clupea pallasii", "actinopterygii", "decapterus", "pogonias cromis", 
                                                                                                                "homarus gammarus", "macrourus berglax", "exopalaemon modestus", 
                                                                                                                "conger conger", "pectinidae", "scorpaeniformes", "siganus", 
                                                                                                                "puntioplites waandersi", "anguilla japonica", "lethrinidae", 
                                                                                                                "sardinella aurita", "gadus chalcogrammus", "scomberomorus niphonius", 
                                                                                                                "exopalaemon modestus", "ariidae", "labeo calbasu", "squillidae", 
                                                                                                                "dicentrarchus labrax", "trichiurus lepturus", "clupeidae", 
                                                                                                                "macrobrachium rosenbergii", "barbonymus gonionotus", "lates calcarifer", 
                                                                                                                "mullus barbatus", "scomber scombrus", "pseudotolithus elongatus", 
                                                                                                                "lutjanidae", "polyprion", "auxis thazard", "penaeus monodon", 
                                                                                                                "bivalvia", "lophiidae", NA, "salmoninae", "boreogadus saida", 
                                                                                                                "raja", "salvelinus fontinalis", "sardina pilchardus", "merluccius", 
                                                                                                                "actinopterygii", "rajiformes", "urophycis tenuis", "procambarus", 
                                                                                                                "seriola", "clarias", "osmerus eperlanus", "sarda", "melanogrammus aeglefinus", 
                                                                                                                "alburnus tarichi", "clupeidae", "nemipteridae", "bagre bagre", 
                                                                                                                "farfantepenaeus brasiliensis", "priacanthus macracanthus", 
                                                                                                                "melanogrammus aeglefinus", "coryphaena hippurus", "sarda sarda", 
                                                                                                                "decapoda", "solea senegalensis", "auxis rochei", "lutjanidae", 
                                                                                                                "pomatomus saltatrix", "micromesistius poutassou", "litopenaeus vannamei", 
                                                                                                                "pomadasys kaakan", "pogonias cromis", "sebastes pinniger", 
                                                                                                                "katsuwonus pelamis", "osphronemus goramy", "actinopterygii", 
                                                                                                                "bivalvia", "selar crumenophthalmus", "decapoda", "anguilla"
                                                      ), habitat = c("marine", "marine", "marine", "marine", "marine", 
                                                                     "marine", "marine", "inland", "unknown", "inland", "marine", 
                                                                     "marine", "unknown", "marine", "marine", "marine", "inland", 
                                                                     "marine", "marine", "marine", "unknown", "marine", "marine", 
                                                                     "marine", "marine", "marine", "marine", "marine", "inland", 
                                                                     "marine", "unknown", "marine", "marine", "inland", "inland", 
                                                                     "marine", "marine", "marine", "marine", "inland", "marine", 
                                                                     "inland", "marine", "marine", "marine", "marine", "inland", 
                                                                     "inland", "marine", "marine", "marine", "marine", "marine", 
                                                                     "marine", "marine", "marine", "inland", "marine", "unknown", 
                                                                     "unknown", "marine", "marine", "inland", "marine", "marine", 
                                                                     "marine", "marine", "marine", "inland", "marine", "inland", 
                                                                     "inland", "marine", "marine", "inland", "marine", "marine", 
                                                                     "marine", "marine", "marine", "marine", "marine", "marine", 
                                                                     "marine", "marine", "marine", "marine", "marine", "marine", 
                                                                     "marine", "marine", "marine", "marine", "marine", "inland", 
                                                                     "marine", "marine", "marine", "unknown", "inland"), method = c("aquaculture", 
                                                                                                                                    "capture", "capture", "capture", "capture", "aquaculture", 
                                                                                                                                    "capture", "capture", "unknown", "capture", "capture", "capture", 
                                                                                                                                    "unknown", "capture", "capture", "capture", "aquaculture", 
                                                                                                                                    "capture", "aquaculture", "capture", "unknown", "capture", 
                                                                                                                                    "capture", "capture", "capture", "capture", "capture", "capture", 
                                                                                                                                    "capture", "capture", "unknown", "capture", "capture", "capture", 
                                                                                                                                    "aquaculture", "capture", "capture", "capture", "capture", 
                                                                                                                                    "capture", "capture", "aquaculture", "capture", "aquaculture", 
                                                                                                                                    "capture", "capture", "aquaculture", "aquaculture", "capture", 
                                                                                                                                    "capture", "capture", "capture", "capture", "capture", "capture", 
                                                                                                                                    "capture", "capture", "capture", "unknown", "unknown", "capture", 
                                                                                                                                    "capture", "aquaculture", "capture", "capture", "capture", 
                                                                                                                                    "capture", "capture", "capture", "capture", "capture", "capture", 
                                                                                                                                    "capture", "capture", "capture", "capture", "capture", "capture", 
                                                                                                                                    "capture", "capture", "capture", "capture", "capture", "capture", 
                                                                                                                                    "aquaculture", "capture", "capture", "capture", "capture", 
                                                                                                                                    "aquaculture", "capture", "capture", "capture", "capture", 
                                                                                                                                    "aquaculture", "aquaculture", "capture", "capture", "unknown", 
                                                                                                                                    "capture"), consumption_type = c("foreign", "domestic", "foreign", 
                                                                                                                                                                     "foreign", "foreign", "foreign", "foreign", "foreign", "foreign", 
                                                                                                                                                                     "foreign", "foreign", "foreign", "foreign", "foreign", "foreign", 
                                                                                                                                                                     "foreign", "foreign", "foreign", "foreign", "foreign", "foreign", 
                                                                                                                                                                     "foreign", "foreign", "foreign", "foreign", "foreign", "foreign", 
                                                                                                                                                                     "foreign", "foreign", "foreign", "foreign", "foreign", "foreign", 
                                                                                                                                                                     "foreign", "foreign", "foreign", "foreign", "foreign", "foreign", 
                                                                                                                                                                     "foreign", "foreign", "foreign", "foreign", "foreign", "foreign", 
                                                                                                                                                                     "foreign", "foreign", "foreign", "foreign", "foreign", "foreign", 
                                                                                                                                                                     "foreign", "domestic", "foreign", "foreign", "foreign", "foreign", 
                                                                                                                                                                     "foreign", "foreign", "foreign", "foreign", "foreign", "foreign", 
                                                                                                                                                                     "foreign", "foreign", "foreign", "foreign", "foreign", "foreign", 
                                                                                                                                                                     "foreign", "foreign", "foreign", "foreign", "foreign", "foreign", 
                                                                                                                                                                     "foreign", "foreign", "foreign", "foreign", "foreign", "foreign", 
                                                                                                                                                                     "foreign", "foreign", "foreign", "foreign", "foreign", "foreign", 
                                                                                                                                                                     "foreign", "foreign", "foreign", "foreign", "foreign", "foreign", 
                                                                                                                                                                     "foreign", "foreign", "foreign", "foreign", "foreign", "foreign", 
                                                                                                                                                                     "foreign"), sciname_hs_modified = c("lates calcarifer", "thunnus alalunga", 
                                                                                                                                                                                                         "metapenaeus", "belone belone", "polynemidae", "litopenaeus stylirostris", 
                                                                                                                                                                                                         "cephalopoda", "alburnus tarichi", NA, "actinopterygii", 
                                                                                                                                                                                                         "micromesistius poutassou", "octopus vulgaris", NA, "sphyraena", 
                                                                                                                                                                                                         "katsuwonus pelamis", NA, "hypophthalmichthys nobilis", "decapterus", 
                                                                                                                                                                                                         "litopenaeus vannamei", "haemulidae", NA, "perca fluviatilis", 
                                                                                                                                                                                                         "clupea pallasii", "actinopterygii", "decapterus", "pogonias cromis", 
                                                                                                                                                                                                         "homarus gammarus", "macrourus berglax", "exopalaemon modestus", 
                                                                                                                                                                                                         "conger conger", "pectinidae", "scorpaeniformes", "siganus", 
                                                                                                                                                                                                         "puntioplites waandersi", "anguilla japonica", "lethrinidae", 
                                                                                                                                                                                                         "sardinella aurita", "gadus chalcogrammus", "scomberomorus niphonius", 
                                                                                                                                                                                                         "exopalaemon modestus", "ariidae", "labeo calbasu", "squillidae", 
                                                                                                                                                                                                         "dicentrarchus labrax", "trichiurus lepturus", "clupeidae", 
                                                                                                                                                                                                         "macrobrachium rosenbergii", "barbonymus gonionotus", "lates calcarifer", 
                                                                                                                                                                                                         NA, "scomber scombrus", "pseudotolithus elongatus", "lutjanidae", 
                                                                                                                                                                                                         NA, "auxis thazard", "penaeus monodon", "bivalvia", "lophiidae", 
                                                                                                                                                                                                         NA, NA, "boreogadus saida", "raja", "salvelinus fontinalis", 
                                                                                                                                                                                                         "sardina pilchardus", "merluccius", "actinopterygii", "rajiformes", 
                                                                                                                                                                                                         "urophycis tenuis", "procambarus", "seriola", "clarias", 
                                                                                                                                                                                                         "osmerus eperlanus", "sarda", "melanogrammus aeglefinus", 
                                                                                                                                                                                                         "alburnus tarichi", "clupeidae", "nemipteridae", "bagre bagre", 
                                                                                                                                                                                                         "farfantepenaeus brasiliensis", "priacanthus macracanthus", 
                                                                                                                                                                                                         "melanogrammus aeglefinus", "coryphaena hippurus", "sarda sarda", 
                                                                                                                                                                                                         "decapoda", "solea senegalensis", "auxis rochei", "lutjanidae", 
                                                                                                                                                                                                         "pomatomus saltatrix", "micromesistius poutassou", "litopenaeus vannamei", 
                                                                                                                                                                                                         "pomadasys kaakan", "pogonias cromis", "sebastes pinniger", 
                                                                                                                                                                                                         "katsuwonus pelamis", "osphronemus goramy", "actinopterygii", 
                                                                                                                                                                                                         "mytilinae", "selar crumenophthalmus", "decapoda", "anguilla"
                                                                                                                                                                     ), consumption_t = c(1.57440252346912, 0.0316272393190406, 
                                                                                                                                                                                          0.117824035037812, 0.0160997158136787, 0.130690279059087, 
                                                                                                                                                                                          2.42512598779201, 0.752117928189641, 1.20382314514808, 0.14672687747532, 
                                                                                                                                                                                          1.37317537466063, 4.76727500000641, 0.201662244509459, 0.381390618731451, 
                                                                                                                                                                                          0.132259713185262, 60.6202875433597, 0.35435441853671, 0.700383464093466, 
                                                                                                                                                                                          0.374115367146049, 2.36219480493487, 1.02138296842922, 1.14244774657431, 
                                                                                                                                                                                          0.126242939500323, 9.70544616057158, 1.13481328390353, 0.239324685816057, 
                                                                                                                                                                                          0.224417235938983, 410.30804126935, 1.25881725786535, 0.0958975215870999, 
                                                                                                                                                                                          2.09336023136151, 1.17461742147966, 0.751604448004045, 0.528686223885288, 
                                                                                                                                                                                          0.409132026505498, 0.800247561236368, 1.97378877329537, 0.0920861499421596, 
                                                                                                                                                                                          44.3147081520301, 1.70012300714244, 1.14471739175944, 0.13955995216635, 
                                                                                                                                                                                          5.39702575582682, 0.183884706141858, 0.388950814165794, 0.568412763327493, 
                                                                                                                                                                                          2.14352245507636, 0.261250271497732, 1.04500682855461, 1.1654623952117, 
                                                                                                                                                                                          0.279964308538319, 0.122865585838159, 2.02826514250659, 213.798223522712, 
                                                                                                                                                                                          0.895957297401221, 7.0354442681002, 0.499725674950841, 0.487471913580811, 
                                                                                                                                                                                          0.789510380085773, 0.261055655212549, 35.059335758829, 5.85321581305863, 
                                                                                                                                                                                          1.32782703743218, 0.978143455224502, 0.244465659065956, 0.993861678853533, 
                                                                                                                                                                                          11.7108921158365, 0.174791471791857, 0.613968785012879, 1.51851754708413, 
                                                                                                                                                                                          0.662324752923305, 0.987267943337352, 0.162575248234922, 
                                                                                                                                                                                          0.00554328892140054, 0.267956880602725, 3.68762926190349, 
                                                                                                                                                                                          0.527597926191333, 5.60032215642305, 24.7859569439911, 0.525054423423039, 
                                                                                                                                                                                          3.31878350423191, 0.0326231637629085, 0.382131022075932, 
                                                                                                                                                                                          0.527073096904947, 0.238317460007832, 0.48579058848678, 0.641241031213629, 
                                                                                                                                                                                          0.44879620330811, 1.96905242206195, 2.15362827414034, 5.00193154847139, 
                                                                                                                                                                                          0.38866747864916, 1.32384787340417, 2.06114561561406, 3.44372272685134, 
                                                                                                                                                                                          0.198514229883201, 0.1635031449133, 2.6928528079472, 1.04610719461944, 
                                                                                                                                                                                          1.91350657656131, 5.09460386702858))

usethis::use_data(mini_consumption, overwrite = TRUE)
